name: Deploy API

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy via SSH with Password
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@api << 'EOF'
            set -e  # Stop execution if any command fails
            
            # Navigate to project directory
            cd /mnt/filestore/hng3/fastapi-book-project
            
            # Pull latest changes from GitHub
            git pull origin main

            # Activate virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install --no-cache-dir -r requirements.txt

            # Restart FastAPI service
            sudo systemctl restart fastapi.service
          EOF